server:
      port: 8181
spring:
    profiles:
      active: local-mysql

---

spring:
  profiles: local-mysql
  datasource:
    url: jdbc:mysql://localhost:3306/gamesdb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        